import {
  CalendarDef,
  FactionDef,
  ItemDef,
  QuestTemplate,
  RegionDef,
  RoleStartDef,
  RouteDef,
  StageChatState,
  StageConfig,
  StageInitState,
  StageMessageState,
  StaticActorTemplate,
  WeatherZoneDef,
  WorldFact,
  WorldRulesDef,
} from "./types";

export const RULESET_VERSION = "medieval-isekai-world-engine-v1";

export const DEFAULT_CONFIG: StageConfig = {
  worldSeed: "medieval-isekai-v1",
  startRegionId: "lumeria-heartlands",
  startRole: "reborn-wanderer",
  survivalMode: "light",
  injuryRealism: "medium",
  weatherPersistence: "medium",
  economyComplexity: "simple",
  showMapPanel: true,
};

export const DEFAULT_CHAT_STATE: StageChatState = {
  exploredLocations: [],
  discoveredLoreEntries: [],
  tutorialFlags: [],
  unlockedSystems: [],
};

export const CALENDAR_DEF: CalendarDef = {
  hoursPerDay: 24,
  minutesPerHour: 60,
  months: [
    { id: "frostwane", name: "Frostwane", season: "Winter", days: 30 },
    { id: "thawmere", name: "Thawmere", season: "Spring", days: 30 },
    { id: "rainmoot", name: "Rainmoot", season: "Spring", days: 30 },
    { id: "bloomtide", name: "Bloomtide", season: "Spring", days: 30 },
    { id: "highsun", name: "Highsun", season: "Summer", days: 30 },
    { id: "emberwake", name: "Emberwake", season: "Summer", days: 30 },
    { id: "harvestmere", name: "Harvestmere", season: "Autumn", days: 30 },
    { id: "leafturn", name: "Leafturn", season: "Autumn", days: 30 },
    { id: "longdusk", name: "Longdusk", season: "Autumn", days: 30 },
    { id: "stormwane", name: "Stormwane", season: "Winter", days: 30 },
    { id: "deepfrost", name: "Deepfrost", season: "Winter", days: 30 },
    { id: "yearsend", name: "Yearsend", season: "Winter", days: 30 },
  ],
};

export const WORLD_RULES: WorldRulesDef = {
  calendarDef: CALENDAR_DEF,
  weatherModelDef: {
    updateStepHours: 4,
    basePersistenceHours: {
      low: 4,
      medium: 8,
      high: 12,
    },
  },
  travelModelDef: {
    fatiguePerTravelHour: 6,
    difficultRouteFatigueBonus: 5,
    severeWeatherMultiplier: 1.35,
    blockedRouteThreshold: 2.1,
  },
  economyModelDef: {
    copperPerSilver: 100,
    silverPerGold: 100,
    goldPerDiamond: 100,
  },
  injuryModelDef: {
    travelStrainThreshold: 72,
    restRecoveryHours: 8,
  },
};

export const WORLD_FACTS: WorldFact[] = [
  {
    id: "fact-lumeria",
    title: "Lumeria",
    summary: "One of the two great continents, marked by kingdoms, neutral settlements, guild routes, and dense biome diversity.",
  },
  {
    id: "fact-orisc",
    title: "Orisc",
    summary: "The sister continent across the Marusa Sea, holding its own cities, wild frontiers, and dangerous crossings.",
  },
  {
    id: "fact-marusa",
    title: "Marusa Sea",
    summary: "The sea between Lumeria and Orisc, haunted by pirate clans, sea monsters, and shifting weather.",
  },
  {
    id: "fact-great-central-mountain",
    title: "Great Central Mountain",
    summary: "A colossal mountain on an island in the Marusa Sea whose upper reaches distort climate, magic, and survival itself.",
  },
];

export const WEATHER_ZONES: WeatherZoneDef[] = [
  {
    id: "temperate-plains",
    name: "Temperate Plains and Valleys",
    climateKind: "temperate",
    seasonalProfiles: {
      Spring: {
        commonConditions: ["clear", "overcast", "mist", "rain"],
        temperatureBand: "temperate",
        precipitationBias: 0.55,
        windBias: 0.35,
        instability: 0.3,
      },
      Summer: {
        commonConditions: ["clear", "clear", "overcast", "rain"],
        temperatureBand: "warm",
        precipitationBias: 0.35,
        windBias: 0.25,
        instability: 0.25,
      },
      Autumn: {
        commonConditions: ["overcast", "mist", "rain", "clear"],
        temperatureBand: "temperate",
        precipitationBias: 0.45,
        windBias: 0.35,
        instability: 0.35,
      },
      Winter: {
        commonConditions: ["overcast", "mist", "snow", "clear"],
        temperatureBand: "cold",
        precipitationBias: 0.3,
        windBias: 0.4,
        instability: 0.3,
      },
    },
    eventPool: [
      {
        id: "spring-thunder",
        label: "Thunderstorm with rain",
        kind: "thunderstorm",
        durationHours: 8,
        intensity: 2,
        resultingCondition: "storm",
      },
      {
        id: "winter-gale",
        label: "Winter storm",
        kind: "winter-storm",
        durationHours: 10,
        intensity: 2,
        resultingCondition: "snow",
      },
    ],
  },
  {
    id: "arcane-mire",
    name: "Ley Marsh and Mist Swamp",
    climateKind: "magical-swamp",
    seasonalProfiles: {
      Spring: {
        commonConditions: ["mist", "rain", "arcane-fog", "overcast"],
        temperatureBand: "temperate",
        precipitationBias: 0.65,
        windBias: 0.15,
        instability: 0.45,
      },
      Summer: {
        commonConditions: ["mist", "overcast", "rain", "arcane-fog"],
        temperatureBand: "warm",
        precipitationBias: 0.55,
        windBias: 0.1,
        instability: 0.35,
      },
      Autumn: {
        commonConditions: ["mist", "arcane-fog", "rain", "overcast"],
        temperatureBand: "temperate",
        precipitationBias: 0.6,
        windBias: 0.15,
        instability: 0.5,
      },
      Winter: {
        commonConditions: ["mist", "overcast", "snow", "arcane-fog"],
        temperatureBand: "cold",
        precipitationBias: 0.35,
        windBias: 0.2,
        instability: 0.45,
      },
    },
    eventPool: [
      {
        id: "acid-drizzle",
        label: "Acid rain",
        kind: "acid-rain",
        durationHours: 6,
        intensity: 3,
        resultingCondition: "acid-rain",
      },
      {
        id: "ley-distortion",
        label: "Arcane distortion front",
        kind: "arcane-distortion",
        durationHours: 12,
        intensity: 2,
        resultingCondition: "arcane-fog",
      },
    ],
  },
  {
    id: "sea-coast",
    name: "Sea Coast and Marusa Crossing",
    climateKind: "coastal",
    seasonalProfiles: {
      Spring: {
        commonConditions: ["clear", "overcast", "rain", "storm"],
        temperatureBand: "temperate",
        precipitationBias: 0.55,
        windBias: 0.55,
        instability: 0.5,
      },
      Summer: {
        commonConditions: ["clear", "clear", "overcast", "storm"],
        temperatureBand: "warm",
        precipitationBias: 0.35,
        windBias: 0.5,
        instability: 0.45,
      },
      Autumn: {
        commonConditions: ["overcast", "rain", "storm", "mist"],
        temperatureBand: "temperate",
        precipitationBias: 0.55,
        windBias: 0.6,
        instability: 0.55,
      },
      Winter: {
        commonConditions: ["overcast", "storm", "snow", "mist"],
        temperatureBand: "cold",
        precipitationBias: 0.45,
        windBias: 0.65,
        instability: 0.5,
      },
    },
    eventPool: [
      {
        id: "sea-typhoon",
        label: "Typhoon front",
        kind: "typhoon",
        durationHours: 12,
        intensity: 3,
        resultingCondition: "storm",
      },
      {
        id: "sudden-showers",
        label: "Scattered showers",
        kind: "scattered-showers",
        durationHours: 4,
        intensity: 1,
        resultingCondition: "rain",
      },
    ],
  },
  {
    id: "cold-highland",
    name: "Cold Highland and Mountain",
    climateKind: "highland",
    seasonalProfiles: {
      Spring: {
        commonConditions: ["overcast", "mist", "snow", "clear"],
        temperatureBand: "cold",
        precipitationBias: 0.35,
        windBias: 0.5,
        instability: 0.35,
      },
      Summer: {
        commonConditions: ["clear", "overcast", "mist", "rain"],
        temperatureBand: "temperate",
        precipitationBias: 0.25,
        windBias: 0.45,
        instability: 0.3,
      },
      Autumn: {
        commonConditions: ["overcast", "mist", "snow", "storm"],
        temperatureBand: "cold",
        precipitationBias: 0.4,
        windBias: 0.55,
        instability: 0.4,
      },
      Winter: {
        commonConditions: ["snow", "snow", "blizzard", "overcast"],
        temperatureBand: "very-cold",
        precipitationBias: 0.5,
        windBias: 0.7,
        instability: 0.45,
      },
    },
    eventPool: [
      {
        id: "summit-blizzard",
        label: "Blizzard front",
        kind: "winter-storm",
        durationHours: 10,
        intensity: 3,
        resultingCondition: "blizzard",
      },
    ],
  },
  {
    id: "central-anomaly",
    name: "Great Central Mountain Anomaly Belt",
    climateKind: "anomaly",
    seasonalProfiles: {
      Spring: {
        commonConditions: ["arcane-fog", "mist", "storm", "clear"],
        temperatureBand: "cold",
        precipitationBias: 0.4,
        windBias: 0.55,
        instability: 0.65,
      },
      Summer: {
        commonConditions: ["arcane-fog", "clear", "storm", "volcanic-ash"],
        temperatureBand: "temperate",
        precipitationBias: 0.25,
        windBias: 0.6,
        instability: 0.7,
      },
      Autumn: {
        commonConditions: ["arcane-fog", "mist", "storm", "volcanic-ash"],
        temperatureBand: "cold",
        precipitationBias: 0.35,
        windBias: 0.6,
        instability: 0.75,
      },
      Winter: {
        commonConditions: ["arcane-fog", "snow", "blizzard", "volcanic-ash"],
        temperatureBand: "very-cold",
        precipitationBias: 0.45,
        windBias: 0.7,
        instability: 0.8,
      },
    },
    eventPool: [
      {
        id: "sulfur-fire-rain",
        label: "Sulfur fire rain",
        kind: "volcanic-eruption",
        durationHours: 8,
        intensity: 3,
        resultingCondition: "volcanic-ash",
      },
      {
        id: "gravity-haze",
        label: "Gravity-laced fog",
        kind: "arcane-distortion",
        durationHours: 6,
        intensity: 2,
        resultingCondition: "arcane-fog",
      },
    ],
  },
];

export const REGIONS: RegionDef[] = [
  {
    id: "lumeria-heartlands",
    name: "Lumeria Heartlands",
    continent: "Lumeria",
    weatherZoneId: "temperate-plains",
    description: "Rolling valleys, meadows, market roads, and neutral farmsteads tied loosely to the routes into Gursa.",
    tags: ["valley", "meadow", "neutral-road"],
  },
  {
    id: "gursa-leymarsh",
    name: "Gursa Leymarsh",
    continent: "Lumeria",
    weatherZoneId: "arcane-mire",
    description: "A misty swamp belt where magical currents thicken around Gursa and the Eter Royal Magic Academy.",
    tags: ["swamp", "arcane", "neutral-city"],
  },
  {
    id: "marusa-western-reach",
    name: "Marusa Western Reach",
    continent: "Marusa Sea",
    weatherZoneId: "sea-coast",
    description: "Wind-cut coastlines and sea lanes watched by traders, smugglers, and pirate spotters.",
    tags: ["coast", "sea-lane", "pirates"],
  },
  {
    id: "great-central-footholds",
    name: "Great Central Footholds",
    continent: "Marusa Sea",
    weatherZoneId: "central-anomaly",
    description: "The lower approaches to the Great Central Mountain, where routes twist under impossible weather and dungeon rumors.",
    tags: ["mountain", "anomaly", "dungeon"],
  },
  {
    id: "orisc-seaboard",
    name: "Orisc Seaboard",
    continent: "Orisc",
    weatherZoneId: "sea-coast",
    description: "An Orisc coastal fringe of briny docks, caravan exchanges, and mercenary contracts.",
    tags: ["coastal", "trade", "frontier-port"],
  },
];

export const LOCATIONS: StageInitState["mapDef"]["locations"] = [
  {
    id: "niria-village",
    name: "Niria",
    regionId: "lumeria-heartlands",
    kind: "village",
    description: "A neutral village of millers, shepherds, and caravan families sitting on the safer branch of the old road.",
    tags: ["neutral", "village", "starting-point"],
    factionIds: [],
    market: true,
    codexEntryId: "loc-niria",
  },
  {
    id: "gursa-city",
    name: "Gursa",
    regionId: "gursa-leymarsh",
    kind: "city",
    description: "A neutral city-state protected by treaties, oaths of non-aggression, and marsh-fed wards against open warfare.",
    tags: ["neutral-city", "trade", "ley-wards"],
    factionIds: ["gursa-treaty-council", "aihalid-guild"],
    market: true,
    codexEntryId: "loc-gursa",
  },
  {
    id: "eter-royal-magic-academy",
    name: "Eter Royal Magic Academy",
    regionId: "gursa-leymarsh",
    kind: "academy",
    description: "The most prestigious magical academy in the setting, rising over ancient ruins and shifting towers above Gursa.",
    tags: ["academy", "magic", "ruins"],
    factionIds: ["eter-royal-magic-academy"],
    market: false,
    codexEntryId: "loc-eter-academy",
  },
  {
    id: "ascalos-watch",
    name: "Ascalos Watch",
    regionId: "marusa-western-reach",
    kind: "frontier",
    description: "A hard-bitten coastal outpost where smugglers, monster hunters, and sea captains barter warnings and grudges.",
    tags: ["frontier", "coast", "dangerous-route"],
    factionIds: ["aihalid-guild"],
    market: true,
    codexEntryId: "loc-ascalos-watch",
  },
  {
    id: "brisco-docks",
    name: "Brisco Docks",
    regionId: "orisc-seaboard",
    kind: "port",
    description: "A neutral port city gateway on the Orisc side, busy with crews, refugees, and hired blades.",
    tags: ["neutral-city", "port", "orisc"],
    factionIds: [],
    market: true,
    codexEntryId: "loc-brisco-docks",
  },
  {
    id: "great-central-foothold",
    name: "Great Central Foothold",
    regionId: "great-central-footholds",
    kind: "wilderness",
    description: "A precarious camp and supply ring on the island below the Great Central Mountain, always one storm from disaster.",
    tags: ["mountain", "wilderness", "marusa"],
    factionIds: [],
    market: true,
    codexEntryId: "loc-great-central-foothold",
  },
  {
    id: "omega-rilias-approach",
    name: "Omega Rilias Fangs Approach",
    regionId: "great-central-footholds",
    kind: "dungeon-approach",
    description: "A lethal approach toward the Beast Dungeon near the center, known for broken expeditions and monster spoor.",
    tags: ["dungeon", "extreme-danger", "beast-dungeon"],
    factionIds: [],
    market: false,
    codexEntryId: "loc-omega-rilias-approach",
  },
];

export const ROUTES: RouteDef[] = [
  {
    id: "route-niria-gursa",
    fromLocationId: "niria-village",
    toLocationId: "gursa-city",
    kind: "road",
    baseTravelMinutes: 360,
    difficulty: 2,
    hazardLevel: 1,
    notes: "A merchant road through temperate meadows and low hills.",
  },
  {
    id: "route-gursa-eter",
    fromLocationId: "gursa-city",
    toLocationId: "eter-royal-magic-academy",
    kind: "canal",
    baseTravelMinutes: 60,
    difficulty: 1,
    hazardLevel: 1,
    notes: "A warded approach by bridgeways and anti-combat ley fields.",
  },
  {
    id: "route-gursa-ascalos",
    fromLocationId: "gursa-city",
    toLocationId: "ascalos-watch",
    kind: "road",
    baseTravelMinutes: 480,
    difficulty: 3,
    hazardLevel: 3,
    notes: "A marsh road where monsters and raiders both test the unwary.",
  },
  {
    id: "route-ascalos-brisco",
    fromLocationId: "ascalos-watch",
    toLocationId: "brisco-docks",
    kind: "sea-lane",
    baseTravelMinutes: 600,
    difficulty: 3,
    hazardLevel: 3,
    notes: "A sea crossing vulnerable to pirate sightings and bad weather.",
  },
  {
    id: "route-ascalos-foothold",
    fromLocationId: "ascalos-watch",
    toLocationId: "great-central-foothold",
    kind: "sea-lane",
    baseTravelMinutes: 540,
    difficulty: 4,
    hazardLevel: 4,
    notes: "A dangerous Marusa passage toward the island of the Great Central Mountain.",
  },
  {
    id: "route-foothold-omega",
    fromLocationId: "great-central-foothold",
    toLocationId: "omega-rilias-approach",
    kind: "mountain-pass",
    baseTravelMinutes: 420,
    difficulty: 5,
    hazardLevel: 5,
    notes: "A lethal ascent through anomaly weather and beast-haunted terrain.",
  },
];

export const FACTIONS: FactionDef[] = [
  {
    id: "aihalid-guild",
    name: "Aihalid Guild",
    kind: "guild",
    homeLocationId: "gursa-city",
    description: "A well-known adventurer guild that pays in gold or diamonds and favors reliable contractors.",
  },
  {
    id: "gursa-treaty-council",
    name: "Gursa Treaty Council",
    kind: "city-authority",
    homeLocationId: "gursa-city",
    description: "The authority that keeps Gursa neutral through magical treaties, mercantile leverage, and sworn mediators.",
  },
  {
    id: "eter-royal-magic-academy",
    name: "Eter Royal Magic Academy",
    kind: "academy",
    homeLocationId: "eter-royal-magic-academy",
    description: "The premier magical institution where many races and kingdoms send students, rivals, and spies.",
  },
  {
    id: "brotherhood-golden-sun",
    name: "Brotherhood of the Golden Sun",
    kind: "hostile",
    homeLocationId: "ascalos-watch",
    description: "A Marusa pirate clan with the reach to disrupt sea lanes and bargain from positions of violence.",
  },
  {
    id: "ardanthal-crown",
    name: "Kingdom of Ardanthal",
    kind: "polity",
    homeLocationId: "niria-village",
    description: "A nearby crown with indirect influence over some inland trade even where neutral charters still hold.",
  },
];

export const ITEM_CATALOG: ItemDef[] = [
  {
    id: "coin-purse",
    name: "Coin Purse",
    description: "A sturdy leather purse used to carry mixed denominations.",
    stackable: false,
    baseValueInCopper: 60,
    tags: ["container", "money"],
    highlight: true,
  },
  {
    id: "trail-rations",
    name: "Trail Rations",
    description: "A bundle of preserved food suitable for road or sea travel.",
    stackable: true,
    baseValueInCopper: 45,
    tags: ["food", "survival"],
    highlight: true,
  },
  {
    id: "waterskin",
    name: "Waterskin",
    description: "A travel waterskin patched for repeated journeys.",
    stackable: false,
    baseValueInCopper: 80,
    tags: ["survival", "drink"],
    highlight: true,
  },
  {
    id: "wool-cloak",
    name: "Wool Cloak",
    description: "A simple cloak that keeps off wind and rain.",
    stackable: false,
    baseValueInCopper: 140,
    tags: ["clothing", "travel"],
    highlight: true,
  },
  {
    id: "iron-knife",
    name: "Iron Knife",
    description: "A serviceable iron knife used for camp work and last-resort defense.",
    stackable: false,
    baseValueInCopper: 190,
    tags: ["weapon", "tool"],
    highlight: true,
  },
  {
    id: "bandage-roll",
    name: "Bandage Roll",
    description: "A simple bandage kit for cuts, strain, and rough travel.",
    stackable: true,
    baseValueInCopper: 65,
    tags: ["medicine", "survival"],
    highlight: true,
  },
  {
    id: "bedroll",
    name: "Bedroll",
    description: "A travel bedroll for camps, inns, and roadside rests.",
    stackable: false,
    baseValueInCopper: 120,
    tags: ["travel", "sleep"],
    highlight: false,
  },
  {
    id: "flint-kit",
    name: "Flint Kit",
    description: "A pouch of tinder and flint for campfires.",
    stackable: false,
    baseValueInCopper: 70,
    tags: ["travel", "tool"],
    highlight: false,
  },
];

export const QUEST_TEMPLATES: QuestTemplate[] = [
  {
    id: "quest-find-your-feet",
    title: "Find Your Feet in a New World",
    summary: "Secure shelter, identify a safe contact, and establish a believable place in your reincarnated life.",
    obligationLevel: "medium",
  },
  {
    id: "quest-gursa-thread",
    title: "Follow the Gursa Thread",
    summary: "Reach Gursa and decide whether the guild, the academy, or the neutral markets offer your best first foothold.",
    obligationLevel: "low",
  },
  {
    id: "quest-marusa-warning",
    title: "Heed the Marusa Warning",
    summary: "Learn why recent sea lanes are tense and whether pirate activity is rising near the Great Central routes.",
    obligationLevel: "medium",
  },
];

export const ROLE_STARTS: RoleStartDef[] = [
  {
    id: "reborn-wanderer",
    label: "Reborn Wanderer",
    startLocationId: "niria-village",
    description: "You awaken in an ordinary rural life with few guarantees but many possible roads.",
    startingMoneyInCopper: 340,
    starterItemIds: [
      { itemId: "coin-purse", quantity: 1 },
      { itemId: "trail-rations", quantity: 2 },
      { itemId: "waterskin", quantity: 1 },
      { itemId: "wool-cloak", quantity: 1 },
      { itemId: "bandage-roll", quantity: 1 },
    ],
    startingQuestIds: ["quest-find-your-feet", "quest-gursa-thread"],
  },
  {
    id: "academy-hopeful",
    label: "Academy Hopeful",
    startLocationId: "gursa-city",
    description: "You arrive close to the academy with more purpose than protection.",
    startingMoneyInCopper: 420,
    starterItemIds: [
      { itemId: "coin-purse", quantity: 1 },
      { itemId: "trail-rations", quantity: 1 },
      { itemId: "waterskin", quantity: 1 },
      { itemId: "wool-cloak", quantity: 1 },
      { itemId: "flint-kit", quantity: 1 },
    ],
    startingQuestIds: ["quest-find-your-feet"],
  },
  {
    id: "caravan-hand",
    label: "Caravan Hand",
    startLocationId: "ascalos-watch",
    description: "You start on the edge of the safer trade world, already exposed to hard routes.",
    startingMoneyInCopper: 390,
    starterItemIds: [
      { itemId: "coin-purse", quantity: 1 },
      { itemId: "trail-rations", quantity: 3 },
      { itemId: "waterskin", quantity: 1 },
      { itemId: "iron-knife", quantity: 1 },
      { itemId: "bedroll", quantity: 1 },
    ],
    startingQuestIds: ["quest-marusa-warning"],
  },
  {
    id: "castaway",
    label: "Castaway",
    startLocationId: "brisco-docks",
    description: "You begin with a disrupted identity and only what survived the sea.",
    startingMoneyInCopper: 180,
    starterItemIds: [
      { itemId: "coin-purse", quantity: 1 },
      { itemId: "waterskin", quantity: 1 },
      { itemId: "wool-cloak", quantity: 1 },
      { itemId: "bandage-roll", quantity: 2 },
    ],
    startingQuestIds: ["quest-find-your-feet", "quest-marusa-warning"],
  },
  {
    id: "minor-noble-exile",
    label: "Minor Noble Exile",
    startLocationId: "gursa-city",
    description: "You start with better coin and worse political certainty.",
    startingMoneyInCopper: 950,
    starterItemIds: [
      { itemId: "coin-purse", quantity: 1 },
      { itemId: "trail-rations", quantity: 2 },
      { itemId: "waterskin", quantity: 1 },
      { itemId: "wool-cloak", quantity: 1 },
      { itemId: "iron-knife", quantity: 1 },
    ],
    startingQuestIds: ["quest-gursa-thread"],
  },
];

export const STATIC_ACTORS: StaticActorTemplate[] = [
  {
    id: "actor-marta-niria",
    locationId: "niria-village",
    name: "Marta of Niria",
    role: "Innkeeper",
    disposition: "friendly",
    note: "Knows road gossip, prices, and who recently passed toward Gursa.",
  },
  {
    id: "actor-sevren-gursa",
    locationId: "gursa-city",
    name: "Sevren Hal",
    role: "Guild Clerk",
    disposition: "neutral",
    factionId: "aihalid-guild",
    note: "Screens new adventurers for the Aihalid Guild hall.",
  },
  {
    id: "actor-professor-iyra",
    locationId: "eter-royal-magic-academy",
    name: "Professor Iyra",
    role: "Ley Theory Lecturer",
    disposition: "guarded",
    factionId: "eter-royal-magic-academy",
    note: "Collects unusual reincarnation stories and notices unstable mana signatures.",
  },
  {
    id: "actor-captain-olvar",
    locationId: "ascalos-watch",
    name: "Captain Olvar",
    role: "Harbor Warden",
    disposition: "guarded",
    note: "Keeps ship movements, pirate sightings, and weather warnings pinned near the watchtower.",
  },
  {
    id: "actor-rime-fang-scout",
    locationId: "omega-rilias-approach",
    name: "Rime Fang Scout",
    role: "Monster Trail Sign",
    disposition: "hostile",
    note: "Fresh spoor and claw marks show the approach is actively dangerous.",
  },
];

export const DEFAULT_SYSTEM_NOTE =
  "Canonical engine state is authoritative for world facts, time, weather, travel, inventory, money, injuries, fatigue, local conditions, and faction standing.";

export const DEFAULT_START_CLOCK = {
  year: 1007,
  month: 2,
  day: 13,
  hour: 7,
  minute: 30,
};

export const EMPTY_INIT_STATE = (config: StageConfig): StageInitState => ({
  worldSeed: config.worldSeed,
  rulesetVersion: RULESET_VERSION,
  worldDef: WORLD_RULES,
  mapDef: {
    worldFacts: WORLD_FACTS,
    regions: [...REGIONS],
    locations: [...LOCATIONS],
    routes: ROUTES,
  },
  factions: FACTIONS,
  weatherZones: WEATHER_ZONES,
  itemCatalog: ITEM_CATALOG,
  roleStarts: ROLE_STARTS,
  questCatalog: QUEST_TEMPLATES,
  staticActors: STATIC_ACTORS,
  config,
});

export const EMPTY_MESSAGE_STATE = (): StageMessageState => ({
  incarnationPhase: "unresolved",
  spawnCandidate: null,
  clock: {
    day: 1,
    month: 1,
    year: 1000,
    hour: 6,
    minute: 0,
    season: "Winter",
    totalMinutes: 0,
  },
  player: {
    roleBackground: null,
    locationId: null,
    regionId: null,
    sublocation: null,
    money: null,
    inventory: [],
    injuries: [],
    fatigue: null,
    reputation: {},
    activeQuests: [],
    party: [],
  },
  world: {
    weatherByRegion: {},
    routeConditions: {},
    settlementStates: {},
    dynamicEvents: [],
    localRumors: {},
    localActors: {},
  },
  scene: {
    visibleActors: [],
    visibleObjects: [],
    immediateHazards: [],
    lastResolvedAction: null,
  },
  softFacts: {
    knownNpcs: [],
    sceneObjects: [],
    rumors: [],
    codexUnlocks: [],
    environmentNotes: [],
  },
  ui: {
    selectedPanel: "overview",
    mapFocusLocationId: null,
    lastEngineNote: "Incarnation not yet resolved.",
  },
});
